apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.apis.abc.com
spec:
  service:
    name: myapi
    namespace: default
    port: 443
  group: apis.abc.com
  version: v1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100

---
apiVersion: v1
kind: Service
metadata:
  name: myapi
spec:
  externalName: www.myapi.com
  type: ExternalName