apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shims.kubesphere.io
spec:
  group: kubesphere.io
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Namespace
          type: string
          jsonPath: .metadata.namespace
        - name: Status
          type: string
          jsonPath: .spec.status
        - name: shadowUid
          type: string
          jsonPath: .spec.shadowUid
        - name: CreationTimestamp
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                status:
                  type: string
                shadowUid:
                  type: string
                CrInfoList:
                  type: array
                  items:
                    type: object
                    properties:
                      group:
                        type: string
                      version:
                        type: string
                      kind:
                        type: string
                      resource:
                        type: string
                      namespace:
                        type: string
                      name:
                        type: string
  scope: Namespaced
  names:
    plural: shims
    singular: shim
    kind: shim